[[products]]
id = "playark-sm"
title = "Discord 顧客管理ソフト"
description = """
Arkプレイヤーの集いの顧客とゲームサーバーを管理するためのシステム。
顧客の契約情報に合わせてゲームサーバー上の権限を同期したりする。"""
skills = ["python", "sqlite", "sqlalchemy", "stripe", "discord"]
link = "https://playark.jp"

[[products]]
id = "rt-discord-bot"
title = "RT Discord Bot"
description = """
中高生の頃に作っていた、Discordコミュニティ管理サービス。現在は私は開発に関与しておらず、[Neody](https://neody.land/)が運営中。
僕のコンピュータ知識の基礎を固めたきっかけ。"""
skills = ["python", "mysql", "linux", "kubernetes", "discord"]
link = "https://rt.neody.land/"

[[products]]
id = "cef-layer-sharing-demo"
title = "CEF Layer Sharing Demo"
description = """
ChatGPT AtlasのOWLアーキテクチャで使われている、プロセス間のChromium画面共有のCEFを使ったデモ。"""
skills = ["rust"]
link = "https://github.com/tasuren/cef-layer-sharing-demo"

[[products]]
id = "monica"
title = "Monica"
description = """
スクリーン上に直接ペンがきができる、プレゼン補助アプリ。
WindowsとMacに対応し、最低限の機能があるシンプルなアプリ。"""
skills = ["tauri", "rust", "typescript", "solid", "html5", "tailwindcss"]
link = "https://github.com/tasuren/monica"

[[products]]
id = "rakugaki-city"
title = "らくがきシティ"
description = """ログイン不要の、開いてすぐ使える、概念説明用シンプル絵チャ。

開いた画面のURLを共有するだけで、他人と絵チャを共有できる。"""
skills = ["typescript", "hono", "html5", "css"]
link = "https://rakugaki.city"

[[products]]
id = "tibani-link"
title = "Tibani Link"
description = """
千葉工業大学生専用の短縮URLサービス。
千葉工業大学のGoogleアカウントでログインすることで、自分の好きな短縮URLを作り放題！"""
skills = [
    "html5",
    "typescript",
    "hono",
    "drizzle",
    "htmx",
    "tailwindcss",
    "cloudflare",
]
link = "https://github.com/sofmes/tibani-link"

[[products]]
id = "window-getter-rs"
title = "window-getter-rs"
description = """
ウィンドウの情報を取得するためのRust向けライブラリ。
WindowsとMacの両方に対応している。"""
skills = ["rust"]
link = "https://github.com/tasuren/window-getter-rs"

[[products]]
id = "window-observer-rs"
title = "window-observer-rs"
description = """
ウィンドウの動きなどを追跡するためのRust向けライブラリ。
WindowsとMacの両方に対応している。
Discordに壁紙を合法的に付けるFreedomWallの後継で使うので実装した。"""
skills = ["rust"]
link = "https://github.com/tasuren/window-observer-rs"

[[products]]
id = "overkami"
title = "overkami (オーバーカミ)"
description = """昔作った[Freedom Wall](https://web.archive.org/web/20231016114730/https://freedom-wall.tasuren.jp/)のリメイク。
アプリを改造せずにアプリに壁紙をつけれる。
tauriとwindow-observer-rsを使って効率的な動作がするようにし、UIも綺麗になった。"""
skills = ["rust", "typescript", "tauri", "solid", "html5", "tailwindcss"]
link = "https://github.com/tasuren/overkami"

[[products]]
id = "shabe2x"
title = "しゃべしゃべ"
description = """
HTMLをコピペできる、シンプルなシャドーイング支援アプリ。
ウェブ音声 APIを使うことで、処理はローカルで完結する。"""
skills = ["html5", "typescript", "solid", "tailwindcss"]
link = "https://shabe2x.tasuren.jp/"

[[products]]
id = "tiwer"
title = "Twier"
description = """
X（旧Twitter）投稿専用クライアント
タイムラインを開けない、文字通り投稿しかできないXクライアント。"""
skills = ["typescript", "tauri"]
link = "https://github.com/tasuren/twier"

[[products]]
id = "website"
title = "ウェブサイト"
description = "今あなたが閲覧中のウェブサイト"
skills = ["html5", "typescript", "astro", "tailwindcss"]
link = "https://github.com/tasuren/website"

[[products]]
id = "dpy-wav-sample"
title = "discord.py wav再生"
description = "discord.pyでFFmpegを使わずにwavファイルを再生するサンプル。"
skills = ["discord", "python"]
link = "https://github.com/tasuren/dpy-wav-sample"

[[products]]
id = "a-synthe"
title = "aSynthe"
description = """
音程検出アプリ
マイクで拾った音の音程をフーリエ変換で求めるだけの単純なアプリ。完全に勉強のために作った、あまり実用性のないもの。"""
skills = ["rust"]
link = "https://github.com/tasuren/a-synthe"

[[products]]
id = "tsuchimod"
title = "土ーと"
description = """
土でダイヤモンドが作れるMinecraftのMOD。
小学６年生くらいの頃に作ったネタMOD。まさかバズるとは思ってなかった。HPのパスワード忘れて更新できない。"""
skills = []
link = "https://tsuchimod.kojyuro.com/"

[[products]]
id = "i21y"
title = "i21y"
description = "Python向けi18nライブラリ  \nYAMLやJSONに対応して、キーを手軽に連結するヘルパー付き。"
skills = ["python"]
link = "https://github.com/tasuren/i21y"

[[products]]
id = "niconico-dl"
title = "niconico-dl"
description = """
Pythonでニコニコ動画をダウンロードするライブラリ。中学３年くらいの頃に多分作ってた。
恐らくもうAPIの変更で動かないので、後継の[niconico.py](https://github.com/niconicolibs/niconico.py)を使うの推奨。"""
skills = ["python"]
link = "https://github.com/tasuren/niconico-dl"

[[products]]
id = "ipcs"
title = "ipcs"
description = """
高校生の頃に作ったWebSocketで多数のクライアントと通信をするためのライブラリ。名前はIPCを由来にしたが、結局RPCとして使えるようにした。
今は使ってなくて更新を放置してる。"""
skills = ["python"]
link = "https://github.com/tasuren/ipcs"
