[[sns]]
id = "bluesky"
link = "https://bsky.app/profile/tasuren.bsky.social"

[[sns]]
id = "instagram"
link = "https://www.instagram.com/tasuren1022/"

[[sns]]
id = "discord"
link = "https://discord.com/users/634763612535390209"

[[sns]]
id = "github"
link = "https://github.com/tasuren"
